name: 'Email Pusher'
description: '定时解析 RSS 并邮件推送新文章'
inputs:
  rss_url:
    description: '博客 RSS 链接'
    required: true
  subscribe_json_url:
    description: '订阅邮箱 JSON 链接'
    required: true
  email_template_url:
    description: '邮件 HTML 模板链接'
    required: true
  smtp_server:
    description: 'SMTP 服务器地址'
    required: true
  smtp_port:
    description: 'SMTP 端口'
    required: true
  smtp_tls:
    description: '是否使用 TLS (true/false)'
    required: true
    default: 'true'
  sender_email:
    description: '发件人邮箱'
    required: true
  blog_info:
    description: 'blog name'
    required: false
    default: 'Blog'
  blog_icon:
    description: 'blog icon'
    required: false
    default: 'https://weekdaycare.cn/asset/avatar.svg'
env:
  SMTP_PASSWORD:
    description: 'SMTP 密码，需设置为 Secret'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'mail'
  color: 'blue'
