name: 'RSS Update Notifier'
description: '定时解析博客 RSS，获取最新文章并邮件推送给订阅邮箱列表'
author: 'weekdaycare'

inputs:
  rss_url:
    description: 'Blog RSS'
    required: true
  subscribe_json_url:
    description: 'Email JSON'
    required: true
  email_template_url:
    description: 'Email HTML Template'
    required: false
  smtp_server:
    description: 'SMTP server'
    required: true
  smtp_tls:
    description: 'use TLS'
    required: true
    default: 'fasle'
  smtp_port:
    description: 'SMTP port'
    required: true
  sender_email:
    description: 'SMTP sender'
    required: true
  blog_info:
    description: 'blog name'
    required: false
    default: 'Blog'
  blog_icon:
    description: 'blog icon'
    required: false
    default: 'https://weekdaycare.cn/asset/avatar.svg'

runs:
  using: 'docker'
  main: 'main.py'

branding:
  icon: 'mail'
  color: 'blue'
